spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthy_life
    username: postgres
    password: 16101992
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

