spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        ddl-auto: none

  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    test-connection: true
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
    debug: true

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

