DROP TABLE IF EXISTS Users CASCADE;

CREATE TABLE IF NOT EXISTS Users
(
    id BIGSERIAL,
    email VARCHAR (65) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role VARCHAR DEFAULT 'USER' NOT NULL
    PRIMARY KEY (id)
);